### ISSUE TITLE
Main site CORS error with jsDelivr API

### ISSUE THREAD

**Issue by sgoblin** [MaxCDN/osscdn#64]
The main site loads everything but the list, then loads forever.

The firefox console says: "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://api.jsdelivr.com/v1/jsdelivr/libraries?fields=name. (Reason: CORS header 'Access-Control-Allow-Origin' does not match '*, *')."

The IE console says: "SEC7118: XMLHttpRequest for http://api.jsdelivr.com/v1/jsdelivr/libraries?fields=name required Cross Origin Resource Sharing (CORS)."

Not tested in Chrome.

Reproducible on different computers running Windows 8 and Windows 7. Not tested on Linux, OSX, BSD, Solaris, or MikeOS.

Internet connection is VIA Rail Canada (Geotool says Internap) and Bell Canada in Ottawa.

**Comment by jimaek** [comment]
It should be fixed now, please try again. (clean your cache)

@jdorfman There was an issue with EdgeRules and purging. It got stuck and none of the rules I had were being applied. Support had no idea why, only after moving to a different cluster it fixed the problem.

**Comment by sgoblin** [comment]
@jimaek Fixed, thanks!

**Comment by jdorfman** [comment]
thank you @jimaek
