### ISSUE TITLE
Add support for SRI

### ISSUE THREAD

**Issue by jonathanKingston** [MaxCDN/osscdn#65]
As a CDN provider it will soon become good practice to provide integrities.
See:
https://github.com/MaxCDN/bootstrap-cdn/issues/555
https://github.com/jsdelivr/jsdelivr/issues/6029
https://github.com/cdnjs/cdnjs/issues/4599

For all static assets that never change can integrities be added?

I'm here to help if anything is needed.

**Comment by mozfreddyb** [comment]
Would be splendid if there were pre-computed `integrity` attributes to use Subresource Integrity with MaxCDN's osscdn.

@jdorfman, can you help us out?

**Comment by jdorfman** [comment]
@mozfreddyb I will see what I can do.

**Comment by jdorfman** [comment]
@jonathanKingston @mozfreddyb I haven't forgotten about this, just working out some details.

**Comment by jdorfman** [comment]
Done-ish =)
