### ISSUE TITLE
HTTPS for osscdn.com?

### ISSUE THREAD

**Issue by leaumar** [MaxCDN/osscdn#67]
It'd be great if osscdn.com had https available. Shouldn't need any explanation to be honest.

If you're looking to avoid costs you can always use letsencrypt for free, works great.

**Comment by jdorfman** [comment]
@TheRealMarnes are you referring to the website (`https://osscdn.com/#/`) or the assets (`//oss.maxcdn.com/slimscroll/1.3.7/jquery.slimscroll.js`) ?

**Comment by leaumar** [comment]
I'd say both. At the moment neither has working https for me. Is it supposed to have?

**Comment by jdorfman** [comment]
The website is lacking https, but the assets aren't:

```
$ curl -I https://oss.maxcdn.com/ripple.js/0.3.2/ripple.min.js
HTTP/1.1 200 OK
Date: Tue, 02 Feb 2016 17:49:53 GMT
Content-Type: application/javascript; charset=utf-8
```

The website will be soon.

**Comment by jdorfman** [comment]
Closing for now
