### ISSUE TITLE
HTTPS broken

### ISSUE THREAD

**Issue by cvrebert** [MaxCDN/osscdn#9]
- http://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js -- works fine
- https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js -- browser flashes SSL certificate warning (domain mismatch), and even if you tell the browser to ignore the warning, the result is a 404.

This is a big problem for us over at Bootstrap ( https://github.com/twbs/bootstrap/issues/11312 ), since we're using HTTPS links to this CDN in our site, docs, examples, etc.  I know HTTPS worked when I originally tested the links, so something seems to have gone wrong since then.

/cc @jdorfman

**Comment by horvatha** [comment]
There is SSL problem again.

```
curl -I https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js
curl: (60) SSL: no alternative certificate subject name matches target host name 'oss.maxcdn.com'
```
